- README.md
The intent is to be explicit about what's development related and to put the install reference at the top of the README
> Adds small changes to the README

- mmomni/ansible/playbooks/mattermost.conf
https://mattermost.atlassian.net/browse/MM-32366
> [MM-32366] Add ipv6 support to nginx

- Makefile
- mattermost-omnibus/DEBIAN/postinst
- mmomni/ansible/playbooks/reconfigure.yml
- mmomni/cmd/reconfigure.go
- omnitests/build.mk
- omnitests/helpers.go
- omnitests/install_test.go
- omnitests/jitsi_test.go
- omnitests/monitoring_test.go
Adds tests for monitoring and jitsi components
https://mattermost.atlassian.net/browse/MM-32706
https://mattermost.atlassian.net/browse/MM-32707
> [MM-32706] Add monitoring and jitsi tests

- mmomni/model/config.go
- mmomni/model/config_test.go
https://mattermost.atlassian.net/browse/MM-32945
> [MM-32945] Validates that JitsiFQDN is different than MM FQDN

- version.yml
The job failed in the release project, because I forgot to actually commit. Next time then!
> Bump PATCH to 1

- version.yml
prepare for mm release 6.0
n/a
> prepare for mm release 6.0

- version.yml
update packge to use mm 6.0.1
after the merge will cherry pick to release-6.0 branch
> update packge to use mm 6.0.1

- version.yml
Cherry pick of #47 on release-6.0.
/cc  @cpanato
```release-note
NONE
```
> Automated cherry pick of #47

- version.yml
bump mm to 6.0.3
after this will push 6.1.0
> bump mm to 6.0.3

- version.yml
- update package to use mm 6.1.0
n/a
> update package to use mm 6.1.0

- version.yml
update omnibus on release 5.37 to version 5.37.6
> update omnibus on release 5.37 to version 5.37.6

- version.yml
update package to use mm 6.2.1
need this to be merged to create the release-6.2 branch
> update package to use mm 6.2.1

- version.yml
update package to use mm 6.3.0
Ticket: https://mattermost.atlassian.net/browse/DOPS-763
> update package to use mm 6.3.0

- version.yml
Ticket: https://mattermost.atlassian.net/browse/DOPS-776
> Update package to use mm 6.3.2

- version.yml
https://mattermost.atlassian.net/browse/DOPS-795
> update mm to 6.3.3

- version.yml
Bump to version 6.4.1
https://mattermost.atlassian.net/browse/DOPS-823
> Bump to version 6.4.1

- version.yml
Bump version v6.6.0
https://mattermost.atlassian.net/browse/DOPS-936
> Bump version v6.6.0

- scripts/repo-setup.sh
We are refactoring `repo-setup.sh` script, to parse positional arguments. 
Thus providing functionality to bypass addition of Nginx,Certbot,PostgreSQL repositories in case of `mattermost` only install
For example will install all repos(mattermost,psql,certbot,nginx): 
```bash
curl -o- https://deb.packages.mattermost.com/repo-setup.sh | sudo bash
or 
curl -o- https://deb.packages.mattermost.com/repo-setup.sh | sudo bash -s all
```  
Will install only mattermost repo:
```bash
curl -o- https://deb.packages.mattermost.com/repo-setup.sh | sudo bash -s mattermost
```
Complements https://github.com/mattermost/mattermost-omnibus/pull/87 
Ticket: https://mattermost.atlassian.net/browse/CLD-4311
> [feat] Refactor repo setup script to accept positional arguments

- Makefile
- mattermost/DEBIAN/postinst
- mattermost/DEBIAN/postrm
- mattermost/DEBIAN/preinst
- mattermost/DEBIAN/prerm
- mattermost/files/mattermost.service
- mattermost/files/omnibus-overrides.conf
- scripts/repo-setup.sh
We have reverted https://github.com/mattermost/mattermost-omnibus/pull/87 https://github.com/mattermost/mattermost-omnibus/pull/88 to assess bugs introduced. 
Described under https://community.mattermost.com/core/pl/kszjhdtkhidr8kd339udn1nwjc 
This, reinstates all reverted commits,  introduced with  https://github.com/mattermost/mattermost-omnibus/pull/87 and .https://github.com/mattermost/mattermost-omnibus/pull/88 , and introduces the following commits to assess bugs: 
- Excluding `/opt/mattermost/mmomni` from deletion, in case of upgrade https://github.com/mattermost/mattermost-omnibus/pull/89/commits/28b962305f6db75ed5bf27a4c600f7a86d2866e3
- Introducing mattermost service overrides to align with omnibus needs. https://github.com/mattermost/mattermost-omnibus/pull/89/commits/290fdb941e …
> Refactoring mattermost package, to suit for distribution 

- mmomni/cmd/backup.go
When running `mmomni backup` I got this error:
```
ERROR: error adding data files to tarball: open /var/opt/mattermost/data/20211209/teams/noteam/channels/.../users/.../.../Image Pasted at 2021-12-9 19-50_thumb.jpg: too many open files
```
Looking at the code, `defer file.Close()` is used inside a loop. This results in all the file handles still being open until the loop terminates and the function returns; if you have many files in the database it's possible to exceed the OS limit.
This change closes the file handle within the loop, whilst retaining the `defer`ed close such that handles are always closed even on error.
I've tested this against my own server, and have validated that it fixes the problem whilst still producing a valid backup. I've also signed the CLA.
> Fix file handle leak in mmomni backup

- mmomni/ansible/playbooks/mattermost.conf
- mmomni/cmd/init.go
- mmomni/model/config.go
Make client_max_body_size configurable in Omnibus
https://github.com/mattermost/mattermost/issues/23994
> MM-53459 Make client_max_body_size configurable in Omnibus

- Makefile
- mattermost-omnibus/files/bionic_dependencies
- scripts/repo-setup.sh
- scripts/sync-and-publish
Ubuntu Bionic is EOL from June 2023
https://wiki.ubuntu.com/Releases
We are stopping support for Ubuntu Bionic with this
Ticket: https://mattermost.atlassian.net/browse/CLD-7472
> [chore] Dropping support for EOL Ubuntu Bionic

- Makefile
- mattermost-omnibus/files/noble_dependencies
- scripts/sync-and-publish
Manual cherrypick of https://github.com/mattermost/mattermost-omnibus/pull/106 to `release-9.10`
https://mattermost.atlassian.net/browse/CLD-7799
> Add Ubuntu Noble support (#106)
